### PR TITLE
Modernize stack and convert to vue+vite

### LINKED ISSUE #65: Degraded Mode
As of today, September 2023, this project is in Degraded Mode

## Broken because of outdated code that does not build anymore

2 weeks ago, I realized [this website was not working.](https://github.com/PrestaShop/PrestaShop/issues/33651)

The [GitHub Action that was supposed to deploy the website was failing](https://github.com/PrestaShop/TopTranslators/actions/runs/5899381854/job/16005540953). After a few easy fixes, the main problem was found: this project is running very outdated Node scripts.

A broad upgrade of NPM and Webpack scripts is needed. The GitHub Action was running npm 8 and failed to download some very old dependencies.

## Workaround

As the website was not even browsable, I found a workaround.

The `/public` directory actually contains the static files that can no longer be computed. They were hardversioned in Git at some point in time. Rather than keeping the whole website down, I submitted a [Pull Request](https://github.com/PrestaShop/TopTranslators/pull/57) that simply [**skips the building of static files**](https://github.com/PrestaShop/TopTranslators/pull/57/commits/bb8af8963d6154bcb59b4184643a33856a590cdc)

So the standard workflow of the website is:
1. It fetches up-to-date Crowdin data
2. It formats data into `statistics.json` file
3. It builds the website static files
4. It deploys the website

I have modified the CI to skip step 3. Currently the GitHub Action workflow does not build the static files anymore: we keep reusing the same, the ones in `/public`.

## Long term solution

The right thing to do, but it needs more time, is to update the NPM dependencies in `/front` application to be able to run in the CI, which can then be piped in again inside the worklow. And resume step 3 instead of skipping it.

Until step 3 is not re-enabled, any change in the code of `/front` will not be active in production environment.

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | There are a lot of outdated deps. This PR migrates from webpack 1 to vite and from React+jQuery to Vue.
| Type?             | refactor
| BC breaks?        | yes
| Deprecations?     | n/a
| Fixed ticket?     | Fixes #65
| Sponsor company   | 
| How to test?      | Manual compare with https://translators.prestashop-project.org/

- From old Webpack 1 to Vite.
- From node 14 to node 20.
- From old js React+jQuery to Vue.
  - For now, its a simple manual component conversion. In the future it could be restructured and refactored.
  - The final bundle size is reduced from 387KB to 71KB.
- Removed a lot of old dependencies.
- It still using Bootstrap 4 alpha, maybe it's better to do a small redesign than try to make it look the same with Bootstrap 5

# Why change to Vite and Vue instead of fixing the dependency problem that existed?

Really old libraries were used, Webpack 1 and a lot of loaders. Due to the breaking changes of new versions of webpack and loaders, it would take me more time than just starting a vue project and migrating a dozen components.

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hi @davidglezz 

I will try to review this PR in next days, it's a big one 😄 

> Really old libraries were used, Webpack 1 and a lot of loaders. Due to the breaking changes of new versions of webpack and loaders, it would take me more time than just starting a vue project and migrating a dozen components.

I agree 👍 code is so old we can simply say we start over from an almost blank page.

Question: don't you think that even Vue or Vite are over-engineered for this site?

When I look at the result I feel like we could almost do it in vanilla JS and using only Bootstrap 😄 . And render the site on server side once, and serve it as static HTML files instead of computing the end result into browser.

**Review by matks — COMMENTED** [review]
This PR needs to run Node 20 to be tested

**Comment by kpodemski** [comment]
wow @davidglezz !

**Comment by davidglezz** [comment]
Thanks
This week I am without laptop because si am on vacations. See you next week 😁

**Comment by matks** [comment]
Before I can test this PR I need to install Node.js 20 on my laptop without breaking my stack 😅 might take a few time

**Review by matthieu-rolland — COMMENTED** [review]
what a PR !

how do we proceed, I guess it should not be tested by QA ?

(@matks if you have nvm installed, you can change node version without breaking anything 👍   )

**Comment by davidglezz** [comment]
@matks 

> Question: don't you think that even Vue or Vite are over-engineered for this site?

Probably yes, a bit, Vue is mainly used as template engine and is the easiest path (for me) to migrate from old react codebase.

Converting to framework-less will require more effort IMO.

**Comment by davidglezz** [comment]
I see other issues:
- Crowdin data is transformed several times, from json to csv to json and finally the js object is mapped to another. This should be simplified.
- Not all languages are rendered/listed. There are 82 languages listed in crowdin vs 67 in `statistics.json`

**Comment by matks** [comment]
Oh yeah there are a loooooot of issues with this repository 😛

**Comment by mflasquin** [comment]
> Before I can test this PR I need to install Node.js 20 on my laptop without breaking my stack 😅 might take a few time

https://github.com/nvm-sh/nvm 😉

**Comment by matks** [comment]
And here we go 😄 troubleshooting brew updates `dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.72.dylib`

EDIT: argh 😭 so many deps to update

**Comment by matks** [comment]
For the record I broke my php + node setup on my laptop 😛 when trying to install Node 20. This is because of https://www.skymac.org/Admin-Dev/article-5038c427-Homebrew-Corriger-un-probleme-de-dependances-trop-recentes.htm

I think I will reinstall my laptop from zero 😄 too many piles of software on it and now it all crumbled.

**Review by matks — CHANGES_REQUESTED** [review]
Hello @davidglezz so today I did the full reinstall of my environment 😄 it's all clean and shiny now! I also installed `nvm` to be able to easily switch Node versions.

I attempted to test your PR but I have this issue: when I browse `front/index.html` I get console error
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "video/mp2t". Strict MIME type checking is enforced for module scripts per HTML spec.
```

Here is what I did:
1. Fetch your branch
2. `cd front`
3. `npm install` using npm 10.1.0
4. `npm run build` using node 20.8.1
5.  Browse index.html

**Comment by davidglezz** [comment]
@matks I'm glad you renewed the node setup successfully.

You can do `npm run dev` (dev build) or
`npm run build && npm run preview` (to preview production build - recommended) or
`npm run build` and serve with other tool the `../public` (not `front/index.html`)

And thank you very much for taking the time to review my PR.

**Comment by davidglezz** [comment]
There are things that are a bit ugly, but that's because I did this in a few hours, I didn't want to spend more time doing some refactoring or improvements without being sure that I'm on the right track and knowing that it could be merge.

Feel free to request any changes or ask me anything you want.

Have a nice day =)

**Comment by matks** [comment]
> @matks I'm glad you renewed the node setup successfully.
> 
> You can do `npm run dev` (dev build) or `npm run build && npm run preview` (to preview production build - recommended) or `npm run build` and serve with other tool the `../public` (not `front/index.html`)
> 
> And thank you very much for taking the time to review my PR.

I did `npm run build` and serve with other tool the `../public` because if I am not wrong this is what the real env will look like.

It works on my machine 🎉 so I think code is "good enough" for now 😄 . This PR is already big, improvements should be done in other PRs.

Now how do we plug this into existing GitHub Action pipeline and test it?

What we could do is create a new branch on this repository, a branch `refacto`, and push updated workflow on this branch. I think I can configure GitHub to build the `refacto` branch on a Environment, allowing us to verify the result. Wdyt?

**Comment by davidglezz** [comment]
I think it's great!

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Branch `refacto` is created. Let's merge this PR into `refacto` and then I will build a test environment for GitHub Actions from `refacto`. I also added the `hacktoberfest` label to the repository 😉 so if you participate in Hacktoberfest this PR will be eligible

**Comment by matks** [comment]
Env configured https://github.com/PrestaShop/TopTranslators/commit/325ec08c4fe968c645ff60c0522bc07e3b913428

**Comment by matks** [comment]
Let's see if it works https://github.com/PrestaShop/TopTranslators/pull/70

**Comment by matks** [comment]
Everything looks good -> https://github.com/PrestaShop/TopTranslators/pull/71 PR to deploy it to prod

If OK for you @davidglezz then tomorrow we can deploy in production

**Comment by davidglezz** [comment]
Perfect!

**Comment by matks** [comment]
@davidglezz Your changes are live.

If you're motivated, there are warnings & notices in the logs https://github.com/PrestaShop/TopTranslators/actions/runs/6571132956/job/17849715207#step:12:1

**Pull request merged**
