### PR TITLE
Support build using Node 16

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Updated everything necessary to make this run with Node 16 (and hopefully fix the build)
| Type?             | bug fix
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]

**Comment by eternoendless** [comment]
It appears that we've entered in dependency hell - webpack will have to be updated alongside its dependencies. Feel free to continue this PR!

**Comment by matks** [comment]
> It appears that we've entered in dependency hell - webpack will have to be updated alongside its dependencies. Feel free to continue this PR!

Is webpack needed at all?

If I look at https://translators.prestashop.com/ I see a static page with a "See more" CTA. I see nothing else moving.

The number of NPM dependencies [in this file](https://github.com/PrestaShop/TopTranslators/blob/prod/front/package.json) do not see to match the complexity of the application in the end. Even Redux and React are required, and I do not see any relevant usage of them. Nothing "reactive".

**Comment by eternoendless** [comment]
I agree that the way it was built clearly seems over-engineered for a modest one pager. However, the alternatives that I see are:

1. Rewrite it using Hugo (likely the simplest choice)
2. Rewrite it using the same stack as Top Contributors (Nuxt + Vue)

Both of them will require some work, but I don't know if it would be more or less than fixing Webpack.

**Review by matks — CHANGES_REQUESTED** [review]
I mark it "requested changes" as CI does not pass

**Comment by matks** [comment]
Hi @eternoendless it looks like we're going to be able to solve this problem with https://github.com/PrestaShop/TopTranslators/pull/68#issuecomment-1769242772 so I close this PR

**Pull request closed without merging**
