### PR TITLE
Build website from Github Actions

### PR DESCRIPTION
**Pull request by Progi1984**

### CODE REVIEW

**Comment by Progi1984** [comment]
@eternoendless Can you tell me why the repository has been moved to PrestaShopCorp Org ?

**Comment by Progi1984** [comment]
@PrestaShopCorp/core & @djodjo3 Migrated from Jenkins to Github Actions as promised ;)

**Comment by eternoendless** [comment]
@Progi1984 No idea, probably because it's private (back when we weren't allowed to have private repos in the PS org). IMO it should be made public and moved back to PrestaShop org. Is there any kind of secret stored in the repo or in its history?

**Comment by Progi1984** [comment]
@eternoendless I check with multiples tools and  not found any kind of secret stored in the repo or in its history.

**Comment by eternoendless** [comment]
In that case we can make it public and move it to the PrestaShop org

**Comment by Progi1984** [comment]
I let you do it @eternoendless. I have no rights.

**Comment by Progi1984** [comment]
Thanks @eternoendless :) 

No it's time to review @PrestaShop/committers & @PrestaShop/prestashop-core-developers

**Review by nicosomb — APPROVED** [review]

**Comment by Progi1984** [comment]
Hi @PrestaShop/committers, I have one approval for @nicosomb. Can I have a second review when you will have some availability, plz ? Thanks

**Review by ga-devfront — COMMENTED** [review]
The GitHub action file looks good to me. However why remove the docker part from the readme and why not add a part for the github action because it is only trigered during a release.

**Comment by Progi1984** [comment]
@ga-devfront Hi, Docker is not used by CD tool so we remove as it is not useful. 

I do the same thing in PrestaShop/TopContributors#85

**Review by ga-devfront — APPROVED** [review]
Ok perfect, thank you for your work !

**Comment by Progi1984** [comment]
Go for merge

**Comment by nicosomb** [comment]
Thank you @Progi1984 !

**Pull request merged**
