### PR TITLE
Explain degraded mode

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Explain degraded mode in readme
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

### CODE REVIEW

**Comment by nicosomb** [comment]
Merged without required approvals !? :trollface:

😅

**Comment by matks** [comment]
As the CI was [completely broken](https://github.com/PrestaShop/PrestaShop/issues/33651), it was impossible to merge any PR, [even the ones that simply added new documentation files](https://github.com/PrestaShop/TopTranslators/pull/55).

I realized the work to fix the CI would be quite long, and that until the CI was fixed, no PR could be merged. Not even a PR to explain the project situation or to give directions about how to deal with this.

So I've been tinkering all morning (see https://github.com/PrestaShop/TopTranslators/pull/57, https://github.com/PrestaShop/TopTranslators/pull/59, https://github.com/PrestaShop/TopTranslators/pull/60, https://github.com/PrestaShop/TopTranslators/pull/61 ...) to make it somehow works, and yes, I forced the merge without approvals or green CI as it would simply never happen 🤷‍♂️ .

This PR https://github.com/PrestaShop/TopTranslators/pull/66 is the last I will do using this method as the explore-and-tinker phase is done:
- https://translators.prestashop-project.org/ is back and running
- the full situation is explained in updated README, giving everyone the needed informations to contribute to fixing it for good

Sometimes the end justifies the means 😉 .

**Comment by nicosomb** [comment]
My comment was only a little troll / joke, don't worry 😘

**Comment by matks** [comment]
I think everyone deserve a transparent explanation 😄

**Pull request merged**
